# LimitRange Reference: https://kubernetes.io/docs/concepts/policy/limit-range/
apiVersion: v1
kind: LimitRange
metadata:
  name: container-limits
spec:
  limits:
  - default:
      cpu: "1"
      memory: 200Mi
    defaultRequest:
      cpu: 10m
      memory: 10Mi
    type: Container
