# config-management.yaml
apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  git:
    syncRepo: https://github.com/haiyanmeng/config-sync-hierarchical-mode-example
    syncBranch: main
    policyDir: config
    secretType: none
  sourceFormat: hierarchy
