---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    configmanagement.gke.io/cluster-name: defaultcluster
    configmanagement.gke.io/source-path: cluster/clusterrolebinding-namespace-reader.yaml
  name: namespace-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: namespace-reader
subjects:
- kind: serviceaccount
  name: sa
  namespace: team-1
- kind: serviceaccount
  name: sa
  namespace: team-2
