apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: non-privileged-pods
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - non-privileged-pods
