# ResourceQuota Reference: https://kubernetes.io/docs/concepts/policy/resource-quotas/
kind: ResourceQuota
apiVersion: v1
metadata:
  name: default-quota
spec:
  hard:
    persistentvolumeclaims: "6"
