---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    configmanagement.gke.io/cluster-name: defaultcluster
    configmanagement.gke.io/source-path: namespaces/team-2/rolebinding-secret-admin.yaml
  name: secret-admin
  namespace: team-2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-admin
subjects:
- kind: ServiceAccount
  name: sa
  namespace: team-2
